[package]
name = "call-node"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[[bin]]
name = "calld"
path = "src/main.rs"

[dependencies]
call-rpc.workspace = true
call-transaction-pool.workspace = true
call-primitives.workspace = true
call-protocol.workspace = true
call-oracle.workspace = true
call-evm.workspace = true
call-precompiles.workspace = true
call-bridge.workspace = true
call-consensus.workspace = true
call-agent.workspace = true
call-shielded.workspace = true
call-crypto.workspace = true
call-chainspec.workspace = true
call-network.workspace = true
call-storage.workspace = true
tokio.workspace = true
jsonrpsee.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
opentelemetry-semantic-conventions.workspace = true
tracing-opentelemetry.workspace = true
axum.workspace = true
reqwest.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
toml = "0.8"
dirs = "5"
sysinfo = "0.33"
fs2 = "0.4"
hex.workspace = true
alloy-primitives.workspace = true
reth-db.workspace = true
k256 = { version = "0.13", features = ["ecdsa"] }
rand.workspace = true
