[package]
name = "call-evm"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
call-primitives.workspace = true
call-protocol.workspace = true
call-precompiles.workspace = true
call-asset.workspace = true
call-validator.workspace = true
call-compliance.workspace = true
call-agent.workspace = true
call-storage.workspace = true
serde.workspace = true
serde_json.workspace = true
revm = { workspace = true, features = ["std"] }
reth-db.workspace = true
reth-db-api.workspace = true
alloy-primitives.workspace = true
alloy-trie.workspace = true
alloy-rlp.workspace = true
hex = "0.4"

[dev-dependencies]
