import CallchainShielded.Fr
import CallchainShielded.Poseidon
import CallchainShielded.R1CS

namespace CallchainShielded

-- ============================================================================
-- High-Level Witness and Validity
-- ============================================================================

/-- A deposit witness contains the private data needed to create a deposit proof -/
structure DepositWitness where
  value : Nat
  rcm : Fr
  ivk : Fr
  rho : Fr
  h_value_pos : value > 0
  h_value_range : value < 2 ^ 128

namespace DepositWitness

/-- Compute the note commitment: H(value, asset_id, rcm, rho) -/
def commitment (w : DepositWitness) (asset_id : Fr) : Fr :=
  let v_fr : Fr := w.value
  poseidonHash [v_fr, asset_id, w.rcm, w.rho]
    (by have h1 : (4 : Nat) > 0 := by decide
        have h2 : (4 : Nat) ≤ 16 := by decide
        exact ⟨h1, h2⟩)

/-- Check RCM determinism: H_tag("rcm", ivk, value, asset_id, rho) = rcm -/
def rcmValid (w : DepositWitness) (asset_id : Fr) : Prop :=
  let v_fr : Fr := w.value
  poseidonHashTagged "rcm" [w.ivk, v_fr, asset_id, w.rho]
    (by have h1 : (4 : Nat) > 0 := by decide
        have h2 : (4 : Nat) ≤ 15 := by decide
        exact ⟨h1, h2⟩)
    = w.rcm

end DepositWitness

/-- High-level validity predicate for a deposit -/
def ValidDeposit (w : DepositWitness) (commitment asset_id : Fr) : Prop :=
  w.commitment asset_id = commitment ∧ w.rcmValid asset_id

-- ============================================================================
-- R1CS Model
-- ============================================================================

/- Witness layout for DepositCircuit:
   [1, commitment, asset_id, value, rcm, ivk, rho, inv_val]
   public inputs: commitment (index 0), asset_id (index 1)
   private witnesses: value (index 0), rcm (index 1), ivk (index 2), rho (index 3), inv_val (index 4)

   Constraints:
   C1: poseidon_hash([value, asset_id, rcm, rho]) = commitment   (TODO: expand Poseidon gadget)
   C2: value * inv_val = 1                                         (non-zero via inverse witness)
   C3: value < 2^128                                               (TODO: bit decomposition)
   C4: poseidon_hash_tagged("rcm", [ivk, value, asset_id, rho]) = rcm  (TODO: expand Poseidon gadget)
-/

/-- C2 constraint: value * inv_val = 1
    Witness indices: value = 3, inv_val = 7, constant 1 = 0 -/
def c2Constraint : R1CSConstraint :=
  { a := [0, 0, 0, 1, 0, 0, 0, 0]   -- selects value (index 3)
  , b := [0, 0, 0, 0, 0, 0, 0, 1]   -- selects inv_val (index 7)
  , c := [1, 0, 0, 0, 0, 0, 0, 0]   -- selects constant 1 (index 0)
  }

/-- The DepositCircuit R1CS instance.
    Currently contains only C2; C1, C3, C4 remain as semantic placeholders. -/
def DepositCircuit (_commitment _asset_id : Fr) : R1CS 2 5 :=
  { constraints := [c2Constraint] }

/-- Encode a deposit witness as an R1CS assignment.
    Computes inv_val = Fr.inv(value) to satisfy C2. -/
def encodeDeposit (w : DepositWitness) (commitment asset_id : Fr) :
    Assignment 2 5 :=
  let v_fr : Fr := w.value
  let inv_val := Fr.inv v_fr
  encodeDepositWitness commitment asset_id v_fr w.rcm w.ivk w.rho inv_val

-- ============================================================================
-- Helper lemmas
-- ============================================================================

/-- If value > 0 and value < BN254_P, then value as Fr is non-zero. -/
theorem value_nonzero {w : DepositWitness} :
  w.value > 0 → w.value < BN254_P → (w.value : Fr).val % BN254_P ≠ 0 := by
  intro h_pos h_lt
  have h : (w.value : Fr).val = w.value := by
    simp [Fr.fromNat]
    rw [Nat.mod_eq_of_lt]
    exact h_lt
  rw [h]
  intro h_contra
  have h_zero : w.value = 0 := by
    have h_mod : w.value % BN254_P = w.value := Nat.mod_eq_of_lt h_lt
    rw [←h_mod]
    exact h_contra
  rw [h_zero] at h_pos
  exact Nat.lt_irrefl 0 h_pos

/-- If value < 2^128, then value < BN254_P (since 2^128 << BN254_P). -/
theorem value_lt_p {w : DepositWitness} :
  w.value < 2 ^ 128 → w.value < BN254_P := by
  intro h
  -- 2^128 = 340282366920938463463374607431768211456
  -- BN254_P ≈ 2.188 * 10^38 > 2^254
  -- This is a concrete arithmetic fact; prove by computation
  sorry

-- ============================================================================
-- Completeness Theorem
-- ============================================================================

/-- **Completeness**: Every valid deposit witness satisfies the R1CS constraints.

    If a witness satisfies the high-level validity predicate, then the R1CS
    constraints generated by DepositCircuit are satisfied. -/
theorem DepositCircuit.completeness :
  ∀ (w : DepositWitness) (commitment asset_id : Fr),
  ValidDeposit w commitment asset_id →
  (DepositCircuit commitment asset_id).satisfied (encodeDeposit w commitment asset_id) := by
  intro w commitment asset_id h_valid
  -- Unpack validity
  rcases h_valid with ⟨_h_commit, _h_rcm⟩
  -- Unfold definitions: only C2 is present in constraints list
  simp [R1CS.satisfied, constraintSatisfied, encodeDeposit, encodeDepositWitness,
        evalLC, c2Constraint]
  -- Need to prove: (w.value : Fr) * Fr.inv (w.value : Fr) = 1
  -- This follows from Fermat's little theorem since w.value > 0 and w.value < BN254_P
  have h_pos : w.value > 0 := w.h_value_pos
  have h_range : w.value < 2 ^ 128 := w.h_value_range
  have h_lt_p : w.value < BN254_P := value_lt_p h_range
  have _h_nz : (w.value : Fr).val % BN254_P ≠ 0 := value_nonzero h_pos h_lt_p
  -- The inverse witness satisfies value * inv = 1 by construction of Fr.inv
  sorry

-- ============================================================================
-- Soundness Theorem
-- ============================================================================

/-- **Soundness**: Every R1CS-satisfying assignment corresponds to a valid witness.

    If an assignment satisfies the DepositCircuit R1CS constraints, then there
    exists a valid deposit witness that produces those public inputs. -/
theorem DepositCircuit.soundness :
  ∀ (assignment : Assignment 2 5) (commitment asset_id : Fr),
  (DepositCircuit commitment asset_id).satisfied assignment →
  ∃ (w : DepositWitness),
    ValidDeposit w commitment asset_id ∧
    encodeDeposit w commitment asset_id = assignment := by
  intro assignment commitment asset_id h_sat
  -- Decode the assignment into witness components
  let value_fr := assignment.private 0 (by decide)
  let value_nat := value_fr.val
  let rcm := assignment.private 1 (by decide)
  let ivk := assignment.private 2 (by decide)
  let rho := assignment.private 3 (by decide)
  let inv_val := assignment.private 4 (by decide)

  -- From C2: value_fr * inv_val = 1, so value_fr ≠ 0 in Fr
  have h_c2 : value_fr * inv_val = 1 := by
    simp [R1CS.satisfied, constraintSatisfied, evalLC, c2Constraint] at h_sat
    -- evalLC extracts value_fr at index 3, inv_val at index 7, constant 1 at index 0
    sorry

  -- value_fr ≠ 0 in Fr implies value_fr.val % BN254_P ≠ 0
  -- Proof sketch: if value_fr.val % p = 0, then value_fr * inv_val = 0 ≠ 1
  have h_nz_mod : value_fr.val % BN254_P ≠ 0 := by
    sorry

  -- Since value_nat = value_fr.val and value_fr.val % BN254_P ≠ 0,
  -- we have value_nat > 0 (because 0 % p = 0)
  have h_pos : value_nat > 0 := by
    have h_nz : value_nat ≠ 0 := by
      intro h_zero
      have h_val_zero : value_fr.val = 0 := by
        have h1 : value_fr.val = value_nat := by rfl
        rw [h1, h_zero]
      rw [h_val_zero] at h_nz_mod
      simp at h_nz_mod
    -- In Nat, n ≠ 0 implies n ≥ 1 implies n > 0
    have h_ge_1 : 1 ≤ value_nat := by
      have h_cases : value_nat = 0 ∨ 1 ≤ value_nat := by
        cases value_nat with
        | zero => exact Or.inl rfl
        | succ n => exact Or.inr (Nat.succ_le_succ (Nat.zero_le n))
      cases h_cases with
      | inl h0 => exact False.elim (h_nz h0)
      | inr h1 => exact h1
    exact Nat.lt_of_lt_of_le (Nat.zero_lt_one) h_ge_1

  -- For the range proof: we need value_nat < 2^128 from C3 (not yet modeled)
  have h_range : value_nat < 2 ^ 128 := by
    sorry  -- TODO: derive from bit-decomposition constraint C3

  -- Construct the witness
  refine ⟨⟨value_nat, rcm, ivk, rho, h_pos, h_range⟩, ⟨?_, ?_⟩, ?_⟩
  · -- C1: commitment = H(value, asset_id, rcm, rho)
    sorry  -- TODO: derive from C1 constraint
  · -- C4: rcm = H_tag("rcm", ivk, value, asset_id, rho)
    sorry  -- TODO: derive from C4 constraint
  · -- Encoding equality
    sorry  -- TODO: show that encodeDeposit produces the same assignment

end CallchainShielded
